from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Dict, Any
import httpx

from app.api.routes.auth import get_current_user
from app.models.user import User
from app.integrations.github_client import GitHubClient
from app.core.config import get_settings

router = APIRouter(prefix="/patches", tags=["patches"])

class CreatePRRequest(BaseModel):
    repo: str
    run_id: int
    file_path: str
    new_content: str
    summary: str = "Automated fix generated by Root Cause CI"

@router.post("/create-pr")
async def create_fix_pr(request: CreatePRRequest, current_user: User = Depends(get_current_user)):
    token = (current_user.github_token if current_user.github_token else None) or get_settings().github_token
    if not token:
        raise HTTPException(status_code=401, detail="GitHub token missing")

    github = GitHubClient(token)

    try:
        # 1. Fetch workflow run to get base branch and SHA
        run_data = await github.get_workflow_run(request.repo, request.run_id)
        base_branch = run_data.get("head_branch")
        commit_sha = run_data.get("head_sha")
        
        if not base_branch or not commit_sha:
            raise HTTPException(status_code=400, detail="Could not determine branch or commit SHA from run.")

        # 2. Create new branch
        new_branch_name = f"orbit-fix-{request.run_id}"
        try:
            await github.create_branch(request.repo, new_branch_name, commit_sha)
        except httpx.HTTPStatusError as e:
            # If 422, it might be because the branch already exists ("Reference already exists").
            if "already exists" not in e.response.text:
                error_detail = e.response.text
                raise HTTPException(status_code=500, detail=f"Failed to create branch: {error_detail}")

        # 3. Create or update file with the new patch content
        commit_message = f"fix: resolve pipeline failure in {request.file_path}\n\n{request.summary}"
        await github.create_or_update_file(
            repo=request.repo,
            file_path=request.file_path,
            message=commit_message,
            content=request.new_content,
            branch=new_branch_name
        )

        # 4. Open PR
        pr_title = f"Fix pipeline failure in {request.file_path} (Run #{request.run_id})"
        pr_body = (
            f"## Root Cause CI Automated Fix\n\n"
            f"This PR was automatically generated to resolve the failure in Pipeline Run #{request.run_id}.\n\n"
            f"**Summary:**\n{request.summary}\n\n"
            f"> Please review the changes before merging. Ensure the sandbox tests have passed."
        )
        
        pr_response = await github.create_pull_request(
            repo=request.repo,
            title=pr_title,
            body=pr_body,
            head=new_branch_name,
            base=base_branch
        )

        return {
            "message": "Pull Request created successfully",
            "pr_url": pr_response.get("html_url"),
            "pr_number": pr_response.get("number")
        }

    except httpx.HTTPStatusError as e:
        error_detail = e.response.text
        raise HTTPException(status_code=e.response.status_code, detail=f"GitHub API Error: {error_detail}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
