from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Dict, Any
import httpx
import hashlib
import json
import subprocess
from pathlib import Path
from tempfile import TemporaryDirectory
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.api.routes.auth import get_current_user
from app.core.database import get_db_session
from app.models.user import User
from app.models.verification_run import VerificationRun
from app.integrations.github_client import GitHubClient
from app.core.config import get_settings
from app.services.patches.scope import validate_unified_patch
from app.services.patches.apply import PatchApplicationError, apply_unified_patch
from app.services.patches.sandbox import DockerSandbox

router = APIRouter(prefix="/patches", tags=["patches"])

class CreatePRRequest(BaseModel):
    repo: str
    run_id: int
    patch: str
    verification_id: int
    allowed_files: list[str]
    summary: str = "Automated fix generated by Root Cause CI"


class VerifyPatchRequest(BaseModel):
    repo: str
    run_id: int
    patch: str
    allowed_files: list[str]
    repository_path: str
    build_command: str = "python -m compileall -q ."
    test_command: str = "pytest -q"
    related_test_command: str | None = None


@router.post("/verify")
def verify_patch(
    request: VerifyPatchRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db_session),
):
    validation = validate_unified_patch(request.patch, set(request.allowed_files))
    patch_digest = hashlib.sha256(request.patch.encode("utf-8")).hexdigest()
    if not validation.valid:
        record = VerificationRun(
            user_id=current_user.id,
            repository=request.repo,
            run_id=str(request.run_id),
            status="PATCH_REJECTED",
            patch_digest=patch_digest,
            modified_files=json.dumps(validation.modified_files),
            reason=validation.reason,
        )
        db.add(record)
        db.commit()
        raise HTTPException(status_code=400, detail=f"Patch rejected: {validation.reason}")

    try:
        workspace = apply_unified_patch(request.repository_path, request.patch)
    except PatchApplicationError as error:
        record = VerificationRun(
            user_id=current_user.id,
            repository=request.repo,
            run_id=str(request.run_id),
            status="PATCH_REJECTED",
            patch_digest=patch_digest,
            modified_files=json.dumps(validation.modified_files),
            reason=f"Patch application failed: {error}",
        )
        db.add(record)
        db.commit()
        raise HTTPException(status_code=422, detail=f"Patch rejected: {error}") from error

    try:
        sandbox_result = DockerSandbox(get_settings().sandbox_image, get_settings().sandbox_timeout_seconds).run(
            workspace.path,
            request.build_command,
            request.test_command,
            request.related_test_command,
        )
    finally:
        result_dict = sandbox_result.as_dict() if "sandbox_result" in locals() else {"status": "SANDBOX_ERROR"}
        workspace.close()

    status_value = "PASSED" if sandbox_result.status == "PASSED" else "FAILED"
    record = VerificationRun(
        user_id=current_user.id,
        repository=request.repo,
        run_id=str(request.run_id),
        status=status_value,
        patch_digest=patch_digest,
        modified_files=json.dumps(validation.modified_files),
        reason=json.dumps(result_dict),
    )
    db.add(record)
    db.commit()
    db.refresh(record)
    if status_value != "PASSED":
        raise HTTPException(status_code=422, detail={"message": "Patch rejected: verification failed.", "verification": result_dict, "verification_id": record.id})
    return {"verification_id": record.id, "status": status_value, "verification": result_dict}

@router.post("/create-pr")
async def create_fix_pr(
    request: CreatePRRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db_session),
):
    validation = validate_unified_patch(request.patch, set(request.allowed_files))
    if not validation.valid:
        raise HTTPException(status_code=400, detail=f"Patch rejected: {validation.reason}")

    verification = db.scalar(
        select(VerificationRun).where(
            VerificationRun.id == request.verification_id,
            VerificationRun.user_id == current_user.id,
            VerificationRun.repository == request.repo,
            VerificationRun.run_id == str(request.run_id),
        )
    )
    patch_digest = hashlib.sha256(request.patch.encode("utf-8")).hexdigest()
    if not verification or verification.status != "PASSED":
        raise HTTPException(status_code=409, detail="Patch rejected: verification has not passed.")
    if verification.patch_digest != patch_digest:
        raise HTTPException(status_code=409, detail="Patch rejected: patch differs from the verified patch.")
    if json.loads(verification.modified_files) != validation.modified_files:
        raise HTTPException(status_code=409, detail="Patch rejected: modified files differ from verification.")

    token = (current_user.github_token if current_user.github_token else None) or get_settings().github_token
    if not token:
        raise HTTPException(status_code=401, detail="GitHub token missing")

    github = GitHubClient(token)

    try:
        # 1. Fetch workflow run to get base branch and SHA
        run_data = await github.get_workflow_run(request.repo, request.run_id)
        base_branch = run_data.get("head_branch")
        commit_sha = run_data.get("head_sha")
        
        if not base_branch or not commit_sha:
            raise HTTPException(status_code=400, detail="Could not determine branch or commit SHA from run.")

        # Apply the verified diff to a temporary copy of the affected GitHub files.
        with TemporaryDirectory(prefix="root-cause-pr-") as temp_dir:
            workspace = Path(temp_dir)
            for file_path in validation.modified_files:
                content = await github.get_file_content(request.repo, file_path, commit_sha)
                if content is None:
                    raise HTTPException(status_code=422, detail=f"Could not fetch {file_path} at the workflow commit.")
                target = workspace / file_path
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")
            patch_file = workspace / "change.patch"
            patch_file.write_text(request.patch, encoding="utf-8")
            applied = subprocess.run(
                ["git", "-C", str(workspace), "apply", "--check", str(patch_file)],
                capture_output=True,
                text=True,
                check=False,
            )
            if applied.returncode != 0:
                raise HTTPException(status_code=422, detail="Verified patch no longer applies to the workflow commit.")
            subprocess.run(["git", "-C", str(workspace), "apply", str(patch_file)], check=True, capture_output=True, text=True)

            # Create new branch only after verification and local application succeed.
            new_branch_name = f"root-cause-fix-{request.run_id}"
            try:
                await github.create_branch(request.repo, new_branch_name, commit_sha)
            except httpx.HTTPStatusError as e:
                if "already exists" not in e.response.text:
                    raise HTTPException(status_code=500, detail=f"Failed to create branch: {e.response.text}") from e

            for file_path in validation.modified_files:
                patched_content = (workspace / file_path).read_text(encoding="utf-8")
                await github.create_or_update_file(
                    repo=request.repo,
                    file_path=file_path,
                    message=f"fix: verified CI failure patch for run {request.run_id}",
                    content=patched_content,
                    branch=new_branch_name,
                )

        pr_title = f"[AI Fix] Fix pipeline failure (Run #{request.run_id})"
        pr_body = (
            f"## Root Cause CI Automated Fix\n\n"
            f"This PR was generated from a constrained, sandbox-verified patch for Pipeline Run #{request.run_id}.\n\n"
            f"**Summary:**\n{request.summary}\n\n"
            f"**Verification:** PASS\n\n"
            f"> Please review the changes before merging. Root Cause CI never auto-merges."
        )
        
        pr_response = await github.create_pull_request(
            repo=request.repo,
            title=pr_title,
            body=pr_body,
            head=new_branch_name,
            base=base_branch
        )

        return {
            "message": "Pull Request created successfully",
            "pr_url": pr_response.get("html_url"),
            "pr_number": pr_response.get("number")
        }

    except httpx.HTTPStatusError as e:
        error_detail = e.response.text
        raise HTTPException(status_code=e.response.status_code, detail=f"GitHub API Error: {error_detail}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
